# Generated by Django 2.2 on 2021-02-12 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('post_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date posted')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, unique_for_date='created', verbose_name='Slug')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=50, verbose_name='Language')),
            ],
        ),
    ]
