# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'fr', 'French')], default=b'en', max_length=50, verbose_name='Language'),
        ),
    ]
