# Generated by Django 3.1.7 on 2023-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0002_update_age_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ebike_class',
            field=models.CharField(blank=True, choices=[('Pedal assist under 20 mph', 'Pedal assist up to 20 mph (32 km/h)'), ('Throttle assist under 20 mph', 'Throttle assist up to 20 mph (32 km/h)'), ('Pedal or throttle assist over 20mph', 'Pedal or throttle assist over 20 mph (32 km/h)')], max_length=40, null=True, verbose_name='What class of e-bike were you riding?'),
        ),
        migrations.AddField(
            model_name='incident',
            name='ebike_speed',
            field=models.CharField(blank=True, choices=[('Under 5 mph', 'Under 5 mph (8 km/h)'), ('Between 5-20 mph', 'Between 5-20mph (8-32 km/h)'), ('Over 20 mph', 'Over 20mph (32 km/h)')], max_length=20, null=True, verbose_name='Approximately what speed was your e-bike traveling at the time?'),
        ),
    ]
