# Generated by Django 3.1.7 on 2023-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0003_add_ebike_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='gender',
            field=models.ManyToManyField(to='mapApp.Gender'),
        ),
    ]
