# Generated by Django 3.1.7 on 2023-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0006_migrate_sex_to_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theft',
            name='insurance_claim',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Did you file an insurance claim?'),
        ),
        migrations.AlterField(
            model_name='theft',
            name='police_report',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Did you file a report with the police?'),
        ),
    ]
