# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0011_auto_20170807_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInfrastructure',
            fields=[
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapApp.Point')),
                ('infra_type', models.CharField(max_length=150, verbose_name='What type of new infrastructure is it?')),
                ('dateAdded', models.DateTimeField(default=None, verbose_name='When was the new infrastructure added?')),
                ('infraDetails', models.TextField(blank=True, default=b'Previously reported incidents and hazards in the area were reset.', max_length=300, null=True, verbose_name='Please give a brief description of the new infrastructure')),
                ('expires_date', models.DateTimeField(blank=True, null=True, verbose_name='When should the new infrastructure icon expire?')),
            ],
            bases=('mapApp.point',),
        ),
        migrations.AddField(
            model_name='point',
            name='infrastructure_changed',
            field=models.BooleanField(default=False, verbose_name='Has the infrastructure been changed?'),
        ),
        migrations.AddField(
            model_name='point',
            name='infrastructure_changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='p_type',
            field=models.CharField(choices=[(b'collision', 'collision'), (b'nearmiss', 'nearmiss'), (b'theft', 'theft'), (b'hazard', 'hazard'), (b'newInfrastructure', 'newInfrastructure'), (b'official', 'official')], max_length=150, verbose_name='Type of report'),
        ),
    ]
