# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0012_auto_20170831_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='aggressive',
            field=models.CharField(blank=True, choices=[(b'Y', 'Yes'), (b'N', 'No'), (b"I don't know", "I don't know")], max_length=50, null=True, verbose_name='Was the driver aggressive?'),
        ),
        migrations.AddField(
            model_name='incident',
            name='intersection',
            field=models.CharField(blank=True, choices=[(b'Y', 'Yes'), (b'N', 'No'), (b"I don't know", "I don't know")], max_length=50, null=True, verbose_name='Did the incident occur at an intersection?'),
        ),
        migrations.AddField(
            model_name='incident',
            name='witness_vehicle',
            field=models.CharField(blank=True, choices=[(b'Bicycle', 'Bicycle'), (b'E-scooter', 'E-scooter'), (b'Pedestrian', 'I was a pedestrian'), (b'Driving', 'I was driving')], max_length=20, null=True, verbose_name='What were you riding?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='bicycle_type',
            field=models.CharField(blank=True, choices=[(b'Personal', "Personal (my own bicycle or a friend's)"), (b'Bike share', 'Bike share'), (b'Bike rental', 'Bike rental'), (b'E-scooter', 'E-scooter')], max_length=20, null=True, verbose_name='What type of bicycle were you riding?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='impact',
            field=models.CharField(choices=[(b'None', 'No impact'), (b'More careful', "I'm now more careful about where/when/how I ride"), (b'Bike less', 'I bike less'), (b'More careful and bike less', "I'm now more careful about where/when/how I ride AND I bike less"), (b'Stopped biking', "I haven't biked since"), (b'Too soon', 'Too soon to say'), (b'Witness', 'I was not directly involved')], max_length=50, null=True, verbose_name='How did this incident impact your bicycling?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_with',
            field=models.CharField(choices=[('Vehicle', ((b'Vehicle, head on', 'Head on'), (b'Vehicle, side', 'Side impact'), (b'Vehicle, angle', 'Angle impact'), (b'Vehicle, rear end', 'Rear end'), (b'Vehicle, turning right', 'Turning right'), (b'Vehicle, turning left', 'Turning left'), (b'Vehicle, passing', 'Passing'), (b'Vehicle, open door', 'Open vehicle door'))), ('Person/animal', ((b'Another cyclist', 'Another cyclist'), (b'Pedestrian', 'Pedestrian'), (b'Animal', 'Animal'), (b'E-scooter', 'E-scooter'))), ('Infrastructure', ((b'Curb', 'Curb'), (b'Train Tracks', 'Train Tracks'), (b'Pothole', 'Pothole'), (b'Lane divider', 'Lane divider'), (b'Sign/Post', 'Sign/Post'), (b'Roadway', 'Roadway'))), (b'Other', 'Other (please describe)')], max_length=100, verbose_name='What sort of object did you collide or nearly collide with?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='injury',
            field=models.CharField(choices=[('Yes', ((b'Injury, no treatment', 'Medical treatment not required'), (b'Injury, saw family doctor', 'Saw a family doctor'), (b'Injury, hospital emergency visit', 'Visited the hospital emergency dept.'), (b'Injury, hospitalized', 'Overnight stay in hospital'))), ('No', ((b'No injury', 'No injury'),)), ('Unknown', ((b'Unknown', "I don't know"),))], max_length=50, verbose_name='Were you injured?'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='personal_involvement',
            field=models.CharField(choices=[(b'Yes', 'Yes, this happened to me'), (b'No', 'No, I witnessed this happen to someone else')], default='NA', max_length=20, verbose_name='Were you directly involved in the incident?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='age',
            field=models.CharField(blank=True, choices=[(b'2006', b'2006'), (b'2005', b'2005'), (b'2004', b'2004'), (b'2003', b'2003'), (b'2002', b'2002'), (b'2001', b'2001'), (b'2000', b'2000'), (b'1999', b'1999'), (b'1998', b'1998'), (b'1997', b'1997'), (b'1996', b'1996'), (b'1995', b'1995'), (b'1994', b'1994'), (b'1993', b'1993'), (b'1992', b'1992'), (b'1991', b'1991'), (b'1990', b'1990'), (b'1989', b'1989'), (b'1988', b'1988'), (b'1987', b'1987'), (b'1986', b'1986'), (b'1985', b'1985'), (b'1984', b'1984'), (b'1983', b'1983'), (b'1982', b'1982'), (b'1981', b'1981'), (b'1980', b'1980'), (b'1979', b'1979'), (b'1978', b'1978'), (b'1977', b'1977'), (b'1976', b'1976'), (b'1975', b'1975'), (b'1974', b'1974'), (b'1973', b'1973'), (b'1972', b'1972'), (b'1971', b'1971'), (b'1970', b'1970'), (b'1969', b'1969'), (b'1968', b'1968'), (b'1967', b'1967'), (b'1966', b'1966'), (b'1965', b'1965'), (b'1964', b'1964'), (b'1963', b'1963'), (b'1962', b'1962'), (b'1961', b'1961'), (b'1960', b'1960'), (b'1959', b'1959'), (b'1958', b'1958'), (b'1957', b'1957'), (b'1956', b'1956'), (b'1955', b'1955'), (b'1954', b'1954'), (b'1953', b'1953'), (b'1952', b'1952'), (b'1951', b'1951'), (b'1950', b'1950'), (b'1949', b'1949'), (b'1948', b'1948'), (b'1947', b'1947'), (b'1946', b'1946'), (b'1945', b'1945'), (b'1944', b'1944'), (b'1943', b'1943'), (b'1942', b'1942'), (b'1941', b'1941'), (b'1940', b'1940'), (b'1939', b'1939'), (b'1938', b'1938'), (b'1937', b'1937'), (b'1936', b'1936'), (b'1935', b'1935'), (b'1934', b'1934'), (b'1933', b'1933'), (b'1932', b'1932'), (b'1931', b'1931'), (b'1930', b'1930'), (b'1929', b'1929'), (b'1928', b'1928'), (b'1927', b'1927'), (b'1926', b'1926'), (b'1925', b'1925'), (b'1924', b'1924'), (b'1923', b'1923'), (b'1922', b'1922'), (b'1921', b'1921'), (b'1920', b'1920'), (b'1919', b'1919'), (b'1918', b'1918'), (b'1917', b'1917'), (b'1916', b'1916'), (b'1915', b'1915'), (b'1914', b'1914'), (b'1913', b'1913'), (b'1912', b'1912'), (b'1911', b'1911'), (b'1910', b'1910'), (b'1909', b'1909'), (b'1908', b'1908'), (b'1907', b'1907')], max_length=15, null=True, verbose_name='What is your birth year?'),
        ),
        migrations.AlterField(
            model_name='point',
            name='details',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Please give a brief description of the incident'),
        ),
    ]
